### ISSUE TITLE
registerPlugin error in Ionic Angular development for iOS

### ISSUE THREAD

**Issue by onexip-vael** [capacitor-community/screen-brightness#2]
**Describe the bug**
After installing the plugin with capacitor 2 and importing the plugin, the following error occurs when trying to use the getBrightness method:

```
Error: ./node_modules/@capacitor-community/screen-brightness/dist/esm/index.js 3:23-37
"export 'registerPlugin' was not found in '@capacitor/core'
    at HarmonyImportSpecifierDependency._getErrors (/Users/vanessa/dev/zeiss/vis.ovs.frontend/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:109:11)
    at HarmonyImportSpecifierDependency.getErrors (/Users/vanessa/dev/zeiss/vis.ovs.frontend/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
    at Compilation.reportDependencyErrorsAndWarnings (/Users/vanessa/dev/zeiss/vis.ovs.frontend/node_modules/webpack/lib/Compilation.js:1463:22)
    at /Users/vanessa/dev/zeiss/vis.ovs.frontend/node_modules/webpack/lib/Compilation.js:1258:10
    at _next0 (eval at create (/Users/vanessa/dev/zeiss/vis.ovs.frontend/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:32:1)
    at eval (eval at create (/Users/vanessa/dev/zeiss/vis.ovs.frontend/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:45:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 @ ./src/app/app.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts
```

**To Reproduce**
1. Install Plugin with 

>     npm install @capacitor-community/screen-brightness
>     npx cap sync

2. import Plugin with

>     import { ScreenBrightness } from '@capacitor-community/screen-brightness';

3. get current brightness with
   `ScreenBrightness.getBrightness().then((currentBrightness) => {
        console.log(currentBrightness);
     });`
4. Build project with

>     npm run build

5. See error

**Expected behavior**
Display of current brightness in console log during runtime.

**Desktop (please complete the following information):**
 - OS: iOS 
 - Browser: -
 - Version: -

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS14.5
 - Browser: -
 - Version: 12.0

**Additional context**
Ionic: 6.14.1
Angular: 11.2.7
Capacitor-CLI: 2.4.7
Capacitor-Core: 2.4.7
Capacitor-iOS: 2.4.7

**Comment by gbkwiatt** [comment]
Having same info on VueJS
```
 warning  in ./node_modules/@capacitor-community/screen-brightness/dist/esm/index.js

"export 'registerPlugin' was not found in '@capacitor/core'

```

and whole project doesn't work, giving me error 
`Uncaught TypeError: Object(...) is not a function`

**Comment by elylucas** [comment]
The plugin is only for Capacitor 3. Going to close this for now but if the issue persists in a Cap 3 project we can look further.
